version: '3.8'

services:
  node:
    image: node:lts
    container_name: main
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run test"
    depends_on:
      - influxdbtest

  influxdbtest:
    image: influxdb:2.7.6-alpine
    container_name: influxtestbase
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=1000
